"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const router = useRouter();
  const [registering,setRegistering]=useState(false); const [username,setUsername]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); const response=await fetch(`/api/session/${registering?"register":"login"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})}); const body=await response.json(); setBusy(false); if(!response.ok){setError(body.error??"Authentication failed.");return;} router.push("/"); router.refresh(); }
  return <main className="flex min-h-screen items-center justify-center px-4"><div className="w-full max-w-sm rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-7 shadow-xl"><h1 className="text-2xl font-bold">Playlist Sync</h1><p className="mt-2 text-sm text-[var(--muted)]">{registering?"Create your private workspace.":"Sign in to your workspace."}</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm">Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 py-2" required minLength={3} maxLength={32}/></label><label className="block text-sm">Password<input type="password" autoComplete={registering?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 py-2" required minLength={8}/></label>{error&&<p className="text-sm text-red-400">{error}</p>}<button disabled={busy} className="w-full rounded-lg bg-[var(--blue)] px-4 py-2 font-semibold text-white disabled:opacity-50">{busy?"Please wait…":registering?"Create account":"Sign in"}</button></form><button onClick={()=>{setRegistering(!registering);setError("");}} className="mt-4 w-full text-sm text-[var(--muted)] hover:text-white">{registering?"Already have an account? Sign in":"Need an account? Register"}</button></div></main>;
}
